# Generated by Django 4.2.16 on 2024-10-20 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriaanimal',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_animal.cadastroanimal'),
        ),
        migrations.AlterField(
            model_name='galeriaanimal',
            name='imagem',
            field=models.ImageField(blank=True, default='img/default.png', upload_to='galeria/'),
        ),
    ]
