# Generated by Django 4.2.16 on 2024-10-20 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_animal', '0002_alter_galeriaanimal_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriaanimal',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='cadastro_animal.cadastroanimal'),
        ),
    ]
