# Generated by Django 4.2.16 on 2024-10-22 23:23

import cadastro_animal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_animal', '0003_alter_galeriaanimal_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriaanimal',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=cadastro_animal.models.upload_to_image),
        ),
    ]
