# Generated by Django 4.2.16 on 2024-10-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_animal', '0004_alter_galeriaanimal_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastroanimal',
            options={'ordering': ['-nome'], 'verbose_name': 'Cadastro de Animal', 'verbose_name_plural': 'Cadastro de Animais'},
        ),
    ]
