# Generated by Django 4.2.16 on 2024-10-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adocao_gestao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regrasadocao',
            old_name='não_devolucao',
            new_name='nao_devolucao',
        ),
    ]
