# Generated by Django 4.2.16 on 2024-10-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao_gestao', '0002_rename_não_devolucao_regrasadocao_nao_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='regrasadocao',
            name='solicitacao',
            field=models.CharField(choices=[('feito', 'Solicitado'), ('andamento', 'Em analise'), ('concluido', 'Adoção aprovada'), ('cancelado', 'Adoção reprovada')], default='Solicitado', max_length=10),
        ),
    ]
