# Generated by Django 4.2.16 on 2024-10-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao_gestao', '0006_alter_cadastroadocao_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroadocao',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
